"""empty message

Revision ID: 6e33a4ddc6a1
Revises: 01cf14725a32
Create Date: 2021-03-31 19:27:45.934407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e33a4ddc6a1'
down_revision = '01cf14725a32'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_datalake():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_vessels')
    # ### end Alembic commands ###


def downgrade_datalake():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass

