"""empty message

Revision ID: ac88df4beb43
Revises: 6e33a4ddc6a1
Create Date: 2021-03-31 19:28:52.271142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac88df4beb43'
down_revision = '6e33a4ddc6a1'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_datalake():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_vessels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('imo', sa.String(length=80), nullable=True),
    sa.Column('tp_id', sa.Integer(), nullable=True),
    sa.Column('so_id', sa.Integer(), nullable=True),
    sa.Column('co_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['co_id'], ['master_companies.id'], ),
    sa.ForeignKeyConstraint(['so_id'], ['master_companies.id'], ),
    sa.ForeignKeyConstraint(['tp_id'], ['master_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_datalake():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_vessels')
    # ### end Alembic commands ###

