"""empty message

Revision ID: d00b9df11e32
Revises: a6b755cd2336
Create Date: 2021-03-31 17:57:41.585635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00b9df11e32'
down_revision = 'a6b755cd2336'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_datalake():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_vessels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('imo', sa.String(length=80), nullable=True),
    sa.Column('tp_id', sa.Integer(), nullable=True),
    sa.Column('so_id', sa.Integer(), nullable=True),
    sa.Column('co_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['co_id'], ['master_companies.id'], ),
    sa.ForeignKeyConstraint(['so_id'], ['master_companies.id'], ),
    sa.ForeignKeyConstraint(['tp_id'], ['master_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_datalake():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_vessels')
    # ### end Alembic commands ###

