"""empty message

Revision ID: d4eac09fc3cd
Revises: d00b9df11e32
Create Date: 2021-03-31 18:25:11.136117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4eac09fc3cd'
down_revision = 'd00b9df11e32'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_datalake():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_vessels')

def downgrade_datalake():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_vessels')
    # ### end Alembic commands ###

